name: Build manager
on:
  push:

jobs:
  build:
    name: Build manager
    runs-on: ubuntu-24.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.32.8
    - run: |
          flutter pub get
          flutter pub run flutter_launcher_icons
          flutter test
          flutter build apk
   #       flutter build appbundle
         
    - name: Upload project
      uses: actions/upload-artifact@v4
      with:
        name: fmanager.tar
        path: ${{ github.workspace }}/build/app/outputs/flutter-apk/app-release.apk
