name: Build manager
on:
  workflow_dispatch:

jobs:
  build:
    name: Build manager
    runs-on: ubuntu-24.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.24.0
    - run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          flutter pub get
          flutter test
          flutter build apk
          flutter build appbundle
         
    - name: Upload project
      uses: actions/upload-artifact@v4
      with:
        name: fmanager.tar
        path: ${{ github.workspace }}/fmanager.tar
