name: Build manager
on:
  push:

jobs:
  build:
    name: Build manager
    runs-on: ubuntu-24.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Build with Gradle
      run: |
          {
            echo 'org.gradle.parallel=true'
            echo 'org.gradle.vfs.watch=true'
            echo 'org.gradle.jvmargs=-Xmx2048m'
            echo 'android.native.buildOutput=verbose'
          } >> gradle.properties
          sed -i 's/org.gradle.configuration-cache=true//g' gradle.properties
          ./gradlew clean assembleRelease

         
    - name: Upload project
      uses: actions/upload-artifact@v4
      with:
        name: fmanager.tar
        path: ${{ github.workspace }}/build/app/outputs/flutter-apk/app-release.apk
